<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'YassaRollbarTest\TestCase'                         => __DIR__ . '/TestCase.php',
    'YassaRollbarTest\Options\ModuleOptionsFactoryTest' => __DIR__ . '/YassaRollbarTest/Options/ModuleOptionsFactoryTest.php',
    'YassaRollbarTest\Options\ModuleOptionsTest'        => __DIR__ . '/YassaRollbarTest/Options/ModuleOptionsTest.php',
);
